# Site settings
title: Iterati's Illuminati
motto: There's always something you don't know you don't know
email: john (dot) jj (dot) miller (at) gmail (dot) com
description: > # this means to ignore newlines until "baseurl:"
  Iterati's projects and thoughts. Information on OSM firmwares and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iterati.github.io" # the base hostname & protocol for your site
github_username:  iterati

# Build settings
markdown: kramdown
