# Site settings
title: Iterati's Illuminati
motto: Iterati's Illuminati - Projects and Thoughts
email: john (dot) jj (dot) miller (at) gmail (dot) com
description: > # this means to ignore newlines until "baseurl:"
  Iterati's projects and thoughts. Information on OSM firmwares and development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iterati.github.io" # the base hostname & protocol for your site
github_username:  iterati

# Build settings
markdown: kramdown

prose:
    rooturl: '_posts'
    siteurl: 'http://iterati.github.io'
    media: '/images'
    metadata:
        _posts:
          - name: "layout"
            field:
                element: "hidden"
                value: "post"
          - name: "title"
            field:
                element: "text"
                label: "Title"
          - name: "category"
            field:
                element: "select"
                label: "Add Category"
                placeholder: "Chose Category"
                options:
                  - name: "OSM"
                    value: "osm"
